### ISSUE TITLE
How-to for testing energy consumption on Android

### ISSUE THREAD

**Issue by lukaszfryc** [mandrigin/status-go-n-wrapper#1]
- [x] create github wiki and describe testing with Android Batterystats & Battery Historian
- [x] describe which tests to perform
- [x] describe how to analyze results, share feedback and where to save the results
- [ ] put out my thoughts about test automation  

This is part of https://github.com/status-im/ideas/issues/83

**Comment by mandrigin** [comment]
@lukaszfryc I'd maybe prefer it to be in markdown. I restructured the repository a little bit. Can you take a look, does it look decent?

**Comment by lukaszfryc** [comment]
@mandrigin looks great :) 

Hm, I don't have much experience with [Github Wiki](https://github.com/mandrigin/status-go-n-wrapper/wiki) but from what I see it is also markdown, has revision history, etc. Maybe the repo would be cleaner if `README.md` will contain only the description of tools (wrappers) + links to how-to of energy testing (described in wiki).  

Anyway, it's a minor thing and we could stay with the current solution as well :)

**Comment by lukaszfryc** [comment]
Btw, I haven't got time today to finish the how-to for Android. Hopefully, it will be done tomorrow.

**Comment by lukaszfryc** [comment]
@mandrigin here e137c7dabc53169563ae086195e389c688320132 I described the tools I used for testing energy consumption on Android.

What I want to do next is to describe the actual tests to perform. Then how to analyze and share results. I've already started here: bd51e77152c56627776656148727976a60cb2b34
The goal is to have test sessions that we can perform before each release + a way to compare results with previous builds. 
What do you think about storing the results (in form of a table + stats.zip) directly in the repo? We could even have a PR template to fill in while performing the tests. Or maybe there is a better way?

**Comment by mandrigin** [comment]
@lukaszfryc we can start with that(storing in the repo), it is simple and straightforward.

Would you mind making a PR with your guides? They look good!

**Comment by lukaszfryc** [comment]
Yeah. And storing it inside the repo could allow us to use Open Bounty and ask community to perform the tests on particular devices we want.

It could look like that - we create an issue describing what tests we want to be performed on what devices (e.g. [the 30 min regression session](https://github.com/mandrigin/status-go-n-wrapper/commit/bd51e77152c56627776656148727976a60cb2b34#diff-d22b92cc1ad3b24930cf7de647c4433cR14)) and then if someone wants to participate she creates a PR. The PR has template with test steps and results. The person also attaches the bugreport.zip / testfairy session link and submits the PR.

I will create the PR tomorrow with the guide.
